### ISSUE TITLE
number of PRs in the last 30 days for repos in rust-lang

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/github-metrics#1]
As a very first step, we can gather the number of PRs in the last 30 days for all repos in rust-lang and dump this data out in CSV format.

It shouldn't be *too* hard to extend the existing loop which dumps out repository names:

https://github.com/nikomatsakis/rust-metrics/blob/e564c4da8f981361dd3ea31019407cc44e98e3d1/src/main.rs#L19-L21

**Comment by chazkiker2** [comment]
Made an initial pass PR to resolve this issue — I'd love feedback from a more experienced rustacean! 

Super happy to make any changes or straight up close the PR if you hate it! No offense will be taken 😃
