### ISSUE TITLE
introduce a metrics.toml configuration file

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/github-metrics#4]
We probably want to support a `~/.metrics.toml` file to load configuration for the user.

Builds on: #2

**Comment by chazkiker2** [comment]
currently claimed by @Llandy3d via [Zulip](https://github-metrics.zulipchat.com/#narrow/stream/291433-general/topic/.234.20toml.20config/near/241853235)

just tossing this here in case anyone missed that message :smile:
